//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace Havit.Distiller.DataLayer.DataSources.Fakes
{
	[Fake]
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public class FakeDistillationResponseSetDataSource : FakeDataSource<Havit.Distiller.Model.DistillationResponseSet>, Havit.Distiller.DataLayer.DataSources.IDistillationResponseSetDataSource
	{
		public FakeDistillationResponseSetDataSource(params Havit.Distiller.Model.DistillationResponseSet[] data)
			: this((IEnumerable<Havit.Distiller.Model.DistillationResponseSet>)data)
		{			
		}

		public FakeDistillationResponseSetDataSource(IEnumerable<Havit.Distiller.Model.DistillationResponseSet> data, ISoftDeleteManager softDeleteManager = null)
			: base(data, softDeleteManager)
		{
		}
	}
}