//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.Patterns.Repositories;

namespace Havit.Distiller.DataLayer.Repositories.Security
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public partial interface ILoginAccountRepository : IRepository<Havit.Distiller.Model.Security.LoginAccount>, IRepositoryAsync<Havit.Distiller.Model.Security.LoginAccount>
	{
	}
}